name: CI

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: "20"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Install Playwright Browsers
        run: npx playwright install chromium
      
      # note: we need to build before running tests because it's a chrome extension
      - name: Test
        run: |
          yarn build   
          yarn test:e2e