name: Publish

on:
  push:
    tags:
      - '*' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
            node-version: '20'
            cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build zip file
        run: yarn build

    #   - name: Upload to Chrome Web Store
    #     uses: mobilefirstllc/cws-publish@latest
    #     with:
    #       action: 'upload' 
    #       client_id: ${{ secrets.CLIENT }}
    #       client_secret: ${{ secrets.SECRET }}
    #       refresh_token: ${{ secrets.TOKEN }}
    #       extension_id: ${{ secrets.EXTENSION_ID }}
    #       zip_file: 'release.zip'